---
resources:
- name: repo
  type: git
  source:
    uri: git@github.com:making/hello-php.git
    private_key: ((github-private-key))
    branch: master
- name: cf
  type: cf
  source:
    api: ((cf-api))
    username: ((cf-username))
    password: ((cf-password))
    organization: ((cf-org))
    space: ((cf-space))
    skip_cert_check: true
jobs:
- name: bootstrap
  serial_groups: [deploy]
  plan:
  - get: repo
  - task: update-manifest
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: orangecloudfoundry/orange-cf-bosh-cli
      inputs:
      - name: repo
      outputs:
      - name: build
      run:
        path: bash
        args:
        - -c
        - |
          set -e
          cp repo/manifest.yml build
  - put: cf
    params:
      manifest: build/manifest.yml
      path: repo
      current_app_name: hello-php-demo
      show_app_log: true
- name: deploy-venerable
  serial_groups: [deploy]
  plan:
  - get: repo
    trigger: true
  - task: update-manifest
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: orangecloudfoundry/orange-cf-bosh-cli
      inputs:
      - name: repo
      outputs:
      - name: build
      run:
        path: bash
        args:
        - -c
        - |
          set -e
          app_name=$(bosh int repo/manifest.yml --path '/applications/0/name')
          echo "update manifest for $app_name"
          bosh int repo/manifest.yml \
            -o <(cat <<EOF
          - type: replace
            path: /applications/0/name
            value: ${app_name}-venerable
          EOF
          ) \
            -o <(cat <<EOF
          - type: replace
            path: /applications/0/instances
            value: 1
          EOF
          ) > build/manifest.yml
          cat build/manifest.yml
  - put: cf
    params:
      manifest: build/manifest.yml
      path: repo
      show_app_log: true
- name: roll-0percent
  serial_groups: [deploy]
  plan:
  - get: repo
    passed:
    - deploy-venerable
  - task: rolling
    params: &CF_PARAMS
      <<: *CF_PARAMS
      CURRENT_DESIRED: 10
      VENERABLE_DESIRED: 0
      INTERVAL_SECONDS: 5
    config:
      <<: *ROLLING
- name: roll-20percent
  serial_groups: [deploy]
  plan:
  - get: repo
    passed:
    - deploy-venerable
  - task: rolling
    params: &CF_PARAMS
      <<: *CF_PARAMS
      CURRENT_DESIRED: 8
      VENERABLE_DESIRED: 2
      INTERVAL_SECONDS: 5
    config:
      <<: *ROLLING
- name: roll-50percent
  serial_groups: [deploy]
  plan:
  - get: repo
    passed:
    - deploy-venerable
  - task: rolling
    params: &CF_PARAMS
      <<: *CF_PARAMS
      CURRENT_DESIRED: 5
      VENERABLE_DESIRED: 5
      INTERVAL_SECONDS: 5
    config:
      <<: *ROLLING
- name: roll-80percent
  serial_groups: [deploy]
  plan:
  - get: repo
    passed:
    - deploy-venerable
  - task: rolling
    params: &CF_PARAMS
      <<: *CF_PARAMS
      CURRENT_DESIRED: 2
      VENERABLE_DESIRED: 8
      INTERVAL_SECONDS: 5
    config:
      <<: *ROLLING
- name: roll-100percent
  serial_groups: [deploy]
  plan:
  - get: repo
    passed:
    - deploy-venerable
  - task: rolling
    params: &CF_PARAMS
      <<: *CF_PARAMS
      CURRENT_DESIRED: 0
      VENERABLE_DESIRED: 10
      INTERVAL_SECONDS: 5
    config:
      <<: *ROLLING
- name: switch
  serial_groups: [deploy]
  plan:
  - get: repo
    passed:
    - roll-100percent
    trigger: true
  - task: switch
    params: &CF_PARAMS
      <<: *CF_PARAMS
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: orangecloudfoundry/orange-cf-bosh-cli
      inputs:
      - name: repo
      outputs:
      - name: build
      run:
        path: bash
        args:
        - -c
        - |
          set -e
          app_name=$(bosh int repo/manifest.yml --path '/applications/0/name')
          venerable_name=${app_name}-venerable
          old_name=${app_name}-old

          cf login -a ${CF_API} --skip-ssl-validation -u ${CF_USERNAME} -p ${CF_PASSWORD} -o ${CF_ORG} -s ${CF_SPACE}

          cf unmap-route ${venerable_name} ${APPS_DOMAIN} --hostname ${venerable_name}
          
          cf d -f ${old_name}
          cf stop ${app_name}
          cf rename ${app_name} ${old_name}
          cf rename ${venerable_name} ${app_name}
params:
  cf: &CF_PARAMS
    CF_API: ((cf-api))
    CF_USERNAME: ((cf-username))
    CF_PASSWORD: ((cf-password))
    CF_ORG: ((cf-org))
    CF_SPACE: ((cf-space))
    APPS_DOMAIN: {{apps-domain}}
  rolling: &ROLLING
    platform: linux
    image_resource:
      type: docker-image
      source:
        repository: orangecloudfoundry/orange-cf-bosh-cli
    inputs:
    - name: repo
    outputs:
    - name: build
    run:
      path: bash
      args:
      - -c
      - |
        set -e
        app_name=$(bosh int repo/manifest.yml --path '/applications/0/name')
        venerable_name=${app_name}-venerable

        cf login -a ${CF_API} --skip-ssl-validation -u ${CF_USERNAME} -p ${CF_PASSWORD} -o ${CF_ORG} -s ${CF_SPACE}
        space_guid=$(cf space ${CF_SPACE} --guid)

        CURRENT=`cf curl "/v2/apps?q=name%3A${app_name}&q=space_guid%3A${space_guid}" | jq -r '.resources[0].entity.instances'`
        VENERABLE=`cf curl "/v2/apps?q=name%3A${venerable_name}&q=space_guid%3A${space_guid}" | jq -r '.resources[0].entity.instances'`

        cf map-route ${venerable_name} ${APPS_DOMAIN} --hostname ${app_name}
        
        echo "FROM: CURRENT=${CURRENT}, VENERABLE=${VENERABLE}"
        echo "TO  : CURRENT=${CURRENT_DESIRED}, VENERABLE=${VENERABLE_DESIRED}"
        while [[ ${CURRENT} != ${CURRENT_DESIRED} || ${VENERABLE} != ${VENERABLE_DESIRED} ]];do
          if [ ${CURRENT} -gt ${CURRENT_DESIRED} ];then
            CURRENT=$(($CURRENT - 1))
          fi
          if [ ${CURRENT} -lt ${CURRENT_DESIRED} ];then
            CURRENT=$(($CURRENT + 1))
          fi
          if [ ${VENERABLE} -gt ${VENERABLE_DESIRED} ];then
            VENERABLE=$(($VENERABLE - 1))
          fi
          if [ ${VENERABLE} -lt ${VENERABLE_DESIRED} ];then
            VENERABLE=$(($VENERABLE + 1))
          fi
          echo "CURRENT=${CURRENT}, VENERABLE=${VENERABLE}"
          cf scale ${venerable_name} -i ${VENERABLE}
          cf scale ${app_name}       -i ${CURRENT}
          sleep ${INTERVAL_SECONDS}
        done
        cf app ${app_name}
        cf app ${venerable_name}